name: Run tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'dependabot/github_actions/*'
      - 'dependabot/npm_and_yarn/*'

env:
  PHP_VERSION: 8.2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📄 Clone repository
        uses: actions/checkout@v5

      - name: ⚙️Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: 🔑 Configure Composer authentication
        run: |
          composer config github-oauth.github.com ${{ secrets.TOKEN_GITHUB }}

      - name: ⬇️Install Composer dependencies
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress --no-ansi --no-interaction --optimize-autoloader

      - name: 🕵️Run PHPStan
        run: composer run analyse

      - name: 🧑‍🔧Run PHP-CS-Fixer
        run: composer run format:check
